<header class="mb-5">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Netfux</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$router->generateUrl("app_home_main");?>">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$router->generateUrl("app_event_index");?>">Évènements</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$router->generateUrl("app_attendee_index");?>">Participants</a>
                    </li>
                    <?php if($user->exist()) : ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$router->generateUrl("app_account_logout");?>">Se
                            Déconnecter</a>
                    </li>
                    <?php else : ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$router->generateUrl("app_account_login");?>">Se
                            Connecter</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$router->generateUrl("app_account_register");?>">S'inscrire</a>
                    </li>
                    <?php endif; ?>
            </div>
        </div>
    </nav>
</header>
