<main class="d-flex h-100 text-center text-white bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto mt-5 flex-column">
        <?php if($messages->exist()) : ?>

        <div class="alert alert-info alert-dismissible fade show col-sm-11 col-md-6 col-lg-6 col-xl-6 mx-auto"
            role="alert">
            <h4 class="alert-heading">Info</h4>
            <?php foreach ($messages->getAndDelete() as $error) : ?>
            <hr>
            <p><?=$error?></p>
            <?php endforeach; ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <?php endif; ?>

        <div class="px-3">
            <h1>
                <?php if($user->exist()): ?>
                <a style="text-decoration:none" href="<?=$router->generateUrl('app_serie_new')?>">
                    <i class="bi bi-patch-plus-fill"></i>
                </a>
                <?php endif; ?> Series
            </h1>
        </div>
        <?php foreach($series as $serie) : ?>
        <div class="container">
            <div class="row bg-light text-dark rounded p-3 mx-auto my-3 align-items-center">
                <div class="col-md-3">
                    <a style="text-decoration: none;"
                        href="<?=$router->generateUrl('app_serie_show', ['id' => $serie->get('id')])?>">
                        <img class="w-100" src="<?=$router->getWwwPath(). '/img/upload/' . $serie->get('picture')?>"
                            alt="">
                    </a>
                </div>
                <div class="col-md-9 text-start">
                    <a class="nav-link" href="<?=$router->generateUrl('app_serie_show', ['id' => $serie->get('id')])?>">
                        <h3 class="display-6"><?=$serie->get('title')?></h3>
                    </a>
                    <p>Synopsis:</p>
                    <p class="border-dark border rounded p-2">
                        <?=$serie->get('description')?>
                    </p>
                    <p>
                        Producteur:
                        <?=$serie->get('director') ? $serie->get('director')->get('firstName') . ' ' . $serie->get('director')->get('lastName') : 'Inconnu'?>
                    </p>
                    <p>
                        Genre: <?=$serie->get('genre') ? $serie->get('genre')->get('name') : 'Inconnu'?>
                    </p>
                    <p>
                        Nombre d'épiosde: <?=$serie->get('numberOfEpisodes')?>.
                    </p>
                    <p>
                        Durée moyenne d'un épiosde: <?=$serie->get('episodeLength')?> minutes.
                    </p>
                    <p>
                        Date de sortie:
                        <?=$serie->get('publishedAt')? $serie->get('publishedAt')->format('m/Y'): "Inconnue"?>
                    </p>
                    <?php if($user->exist()): ?>
                    <div class="col-12 d-flex justify-content-end d-flex">

                        <a class="btn btn-warning "
                            href="<?=$router->generateUrl('app_serie_edit',['id' => $serie->get("id")])?>">Modifier</a>

                        <a class="btn btn-danger "
                            href="<?=$router->generateUrl('app_serie_delete',['id' => $serie->get("id")])?>">Supprimer</a>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</main>
