<main>
    <h1 class="display-3 text-center my-2">Nouvelle serie</h1>
    <?php if($messages->exist()) : ?>
    <div class="alert alert-danger alert-dismissible col-sm-11 col-md-6 col-lg-6 col-xl-6 mx-auto">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <h4 class="alert-heading">Des erreurs ont été détéctés</h4>
        <?php foreach ($messages->getAndDelete() as $error) : ?>
        <hr>
        <p><?=$error?></p>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <div class="row">
        <div class="bg-dark text-light py-4 px-5 rounded col-sm-11 col-md-6 col-lg-6 col-xl-6 mx-auto my-3">
            <form action="" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="title">Titre*</label>
                    <input type="text" id="title" name="title" class="form-control" value="<?=$serie->get('title')?>">
                </div>
                <div class="form-group">
                    <label for="description">Description*</label>
                    <textarea name="description" class="form-control"><?=$serie->get('description')?></textarea>
                </div>
                <div class="form-group">
                    <label for="numberOfEpisodes">Nombre d'épisodes*</label>
                    <input type="number" id="numberOfEpisodes" name="numberOfEpisodes" class="form-control"
                        value="<?=$serie->get('numberOfEpisodes')?>">
                </div>
                <div class="form-group">
                    <label for="episodeLength">Durée d'un épisode (en minutes)*</label>
                    <input type="number" id="episodeLength" name="episodeLength" class="form-control"
                        value="<?=$serie->get('episodeLength')?>">
                </div>
                <div class="form-group">
                    <label for="publishedAt">Date de sortie*</label>
                    <input type="date" id="publishedAt" name="publishedAt" class="form-control"
                        value="<?=$editMode && $serie->get('publishedAt')? $serie->get('publishedAt')->format('Y-m-d'): ""?>">
                </div>
                <div class="form-group">
                    <label for="directorId">Directeur*</label>
                    <select class="form-select" name="directorId" id="directorId">
                        <?php foreach($directors as $director): ?>
                        <option value=" <?=$director->get('id') ?>"
                            <?=$serie->get('directorId') && $serie->get('directorId') === $director->get('id') ? "selected": null ?>>
                            <?=$director->get('firstName') . " " . $director->get('lastName') ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="genreId">Genre*</label>
                    <select class="form-select" name="genreId" id="genreId">
                        <?php foreach($genres as $genre): ?>
                        <option value="<?=$genre->get('id') ?>"
                            <?=$serie->get('genreId') && $serie->get('genreId') === $genre->get('id') ? "selected": null ?>>
                            <?=$genre->get('name') ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="idYoutube">Id Youtube*</label>
                    <input type="text" id="idYoutube" name="idYoutube" class="form-control"
                        value="<?=$serie->get('idYoutube')?>">
                </div>
                <?php if($serie->get('picture')): ?>
                <div class="border-primary rounded w-75 mx-auto my-3">

                    <img class="w-100"
                        src="<?=$router->getWwwPath(). $env->get('PUBLIC_UPLOAD_DIR') . $serie->get('picture')?>"
                        alt="">
                </div>
                <?php endif; ?>
                <div class="form-group">
                    <label for="picture">Image</label>
                    <input type="file" id="picture" name="picture" class="form-control" lang="fr">
                </div>
                <input type="submit" value="Ajouter" class="btn btn-primary mx-auto my-3">
            </form>
        </div>
    </div>
</main>
