<main>
    <h1><?=htmlspecialchars($title)?></h1>
    <?php if($messages->exist()) : ?>
    <div class="alert alert-danger col-sm-11 col-md-6 col-lg-6 col-xl-6 mx-auto" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="alert-heading">Des erreurs ont été détéctés</h4>
        <?php foreach ($messages->getAndDelete() as $error) : ?>
        <hr>
        <p><?=$error?></p>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-sm-11 col-md-6 col-lg-6 col-xl-6 mx-auto">
            <form action="" method="post">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" id="email" name="email" class="form-control">
                </div>
                <div class="form-group">
                    <label for="password">Mot de passe</label>
                    <input type="password" id="password" name="password" class="form-control">
                </div>
                <input type="submit" value="Se Connecter" class="btn btn-primary">
            </form>
        </div>
    </div>
</main>
