<main class="d-flex h-100 text-center text-white bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto mt-5 flex-column">
        <h1><?=htmlspecialchars($title)?></h1>
        <?php if($messages->exist()) : ?>
        <div class="alert alert-danger col-sm-11 col-md-4 col-lg-4 col-xl-4 mx-auto" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            <h4 class="alert-heading">Des erreurs ont été détéctés</h4>
            <?php foreach ($messages->getAndDelete() as $error) : ?>
            <hr>
            <p><?=$error?></p>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-sm-11 col-md-6 col-lg-4 col-xl-4 mx-auto">
                <form action="" method="post">
                    <div class="form-group mt-3">
                        <label for="email">Email</label>
                        <input type="text" id="email" name="email" class="form-control mt-2">
                    </div>
                    <div class="form-group mt-3">
                        <label for="password">Mot de passe</label>
                        <input type="password" id="password" name="password" class="form-control mt-2">
                    </div>
                    <input type="submit" value="Se Connecter" class="btn btn-primary my-5 py-2 w-75">
                </form>
            </div>
        </div>
    </div>
</main>
