<main class="d-flex h-100 text-center text-white bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto mt-5 flex-column">
        <h1><?=htmlspecialchars($title)?></h1>
        <?php if($messages->exist()) : ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">Des erreurs ont été détéctés</h4>
            <?php foreach ($messages->getAndDelete() as $error) : ?>
            <hr>
            <p><?=$error?></p>
            <?php endforeach; ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-sm-11 col-md-6 col-lg-4 col-xl-4 mx-auto">
                <form action="" method="post">
                    <div class="form-group mt-3">
                        <label for="fname">Prénom*</label>
                        <input type="text" id="fname" name="fname" class="form-control mt-2" placeholder="John"
                            value="<?=isset($registering )? $registering->get("firstName") : ""?>">
                    </div>
                    <div class="form-group mt-3">
                        <label for="lname">Nom*</label>
                        <input type="text" id="lname" name="lname" class="form-control mt-2" placeholder="Doe"
                            value="<?=isset($registering )? $registering->get("lastName") : ""?>">
                    </div>
                    <div class="form-group mt-3">
                        <label for="email">Email*</label>
                        <input type="email" id="email" name="email" class="form-control mt-2"
                            placeholder="jdoe@exemple.com"
                            value="<?=isset($registering )? $registering->get("email") : ""?>">
                    </div>
                    <div class="form-group mt-3">
                        <label for="password">Mot de passe*</label>
                        <input type="password" id="password" name="password" class="form-control mt-2"
                            placeholder="***********">
                        <small class="float-start mt-1" style="font-size:x-small">* 8 caractères, 1 majuscule, 1
                            minuscule, 1 caractère spéciale
                            et 1 chiffre au minimum
                        </small>
                    </div>
                    <input type="submit" value="S'inscrire" class="btn btn-primary my-5 py-2 w-75">
                </form>
            </div>
        </div>
    </div>
</main>
