<main>
    <h1 class="display-3 text-center my-2"><?=($editMode) ? $movie->get('title') :"Nouveau Film" ?></h1>
    <?php if($messages->exist()) : ?>

    <div class="alert alert-danger alert-dismissible fade show col-sm-11 col-md-6 col-lg-6 col-xl-6 mx-auto"
        role="alert">
        <h4 class="alert-heading">Des erreurs ont été détéctés</h4>
        <?php foreach ($messages->getAndDelete() as $error) : ?>
        <hr>
        <p><?=$error?></p>
        <?php endforeach; ?>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <?php endif; ?>
    <div class="row">
        <div class="bg-dark text-light py-4 px-5 rounded col-sm-11 col-md-6 col-lg-6 col-xl-6 mx-auto my-3">
            <form action="" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="title">Titre*</label>
                    <input type="text" id="title" name="title" class="form-control" value="<?=$movie->get('title')?>">
                </div>
                <div class="form-group">
                    <label for="description">Description*</label>
                    <textarea name="description" class="form-control"><?=$movie->get('description')?></textarea>
                </div>
                <div class="form-group">
                    <label for="length">Durée (en minutes)*</label>
                    <input type="number" id="length" name="length" class="form-control"
                        value="<?=$movie->get('length')?>">
                </div>
                <div class="form-group">
                    <label for="directorId">Directeur*</label>
                    <select class="form-select" name="directorId" id="directorId">
                        <?php foreach($directors as $director): ?>
                        <option value=" <?=$director->get('id') ?>"
                            <?=$movie->get('directorId') && $movie->get('directorId') === $director->get('id') ? "selected": null ?>>
                            <?=$director->get('firstName') . " " . $director->get('lastName') ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="genreId">Genre*</label>
                    <select class="form-select" name="genreId" id="genreId">
                        <?php foreach($genres as $genre): ?>
                        <option value="<?=$genre->get('id') ?>"
                            <?=$movie->get('genreId') && $movie->get('genreId') === $genre->get('id') ? "selected": null ?>>
                            <?=$genre->get('name') ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="idYoutube">Id Youtube*</label>
                    <input type="text" id="idYoutube" name="idYoutube" class="form-control"
                        value="<?=$movie->get('idYoutube')?>">
                </div>
                <div class="form-group">
                    <label for="publishedAt">Date de sortie*</label>
                    <input type="date" id="publishedAt" name="publishedAt" class="form-control"
                        value="<?=$editMode && $movie->get('publishedAt')? $movie->get('publishedAt')->format('Y-m-d'): ""?>">
                </div>
                <?php if($movie->get('picture')): ?>
                <div class="border-primary rounded w-75 mx-auto my-3">

                    <img class="w-100"
                        src="<?=$router->getWwwPath(). $env->get('PUBLIC_UPLOAD_DIR') . $movie->get('picture')?>"
                        alt="">
                </div>
                <?php endif; ?>
                <div class=" form-group">
                    <label for="picture">Image*</label>
                    <input type="file" id="picture" name="picture" class="form-control" lang="fr">
                </div>
                <input type="submit" value="Ajouter" class="btn btn-primary mx-auto my-3">
            </form>
        </div>
    </div>
</main>
