<main class="d-flex h-100 text-center text-white bg-dark">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto mt-5 flex-column">

        <div class="px-3">
            <h1><?=$movie->get('title')?></h1>
        </div>
        <div class="container">
            <div class="row bg-light text-dark rounded p-3 mx-auto my-3 align-items-center">
                <div class="col-12">
                    <a href="<?=$router->generateUrl('app_movie_index')?>" class="btn btn-info float-start">Retour
                        à la
                        liste des films</a>
                </div>
                <div class="col-md-5 mx-auto rounded my-3" style="width: 50vw;height:28vw">
                    <iframe style="width: 50vw;height:28vw" class="rounded"
                        src="https://www.youtube.com/embed/<?=$movie->get('idYoutube')?>" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>

                </div>
                <div class="col-12 text-start">
                    <p>Synopsis:</p>
                    <p class="border-dark border rounded p-2">
                        <?=$movie->get('description')?>
                    </p>
                    <p>
                        Producteur: <?=$movie->get('director')->get('firstName')?>
                        <?=$movie->get('director')->get('lastName')?>
                    </p>
                    <p>
                        Genre: <?=$movie->get('genre')->get('name')?>
                    </p>
                    <p>
                        Durée: <?=$movie->get('length')?> minutes.
                    </p>
                    <?php if($user->exist()): ?>
                    <a class="btn btn-warning w-100"
                        href="<?=$router->generateUrl('app_movie_edit',['id' => $movie->get("id")])?>">Modifier</a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</main>
