<main>
    <h1 class="display-3 text-center my-2"><?= $editMode ? "Edition" : "Nouveau"?> Participant</h1>
    <?php if($messages->exist()) : ?>
    <div class="alert alert-danger alert-dismissible col-sm-11 col-md-6 col-lg-6 col-xl-6 mx-auto">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <h4 class="alert-heading">Des erreurs ont été détéctés</h4>
        <?php foreach ($messages->getAndDelete() as $error) : ?>
        <hr>
        <p><?=$error?></p>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <div class="row">
        <div class="bg-dark text-light py-4 px-5 rounded col-sm-11 col-md-6 col-lg-6 col-xl-6 mx-auto my-3">
            <form action="" method="post">
                <div class="form-group  mt-2">
                    <label for="firstName">Prénom*</label>
                    <input type="text" id="firstName" name="firstName" class="form-control"
                        value="<?=$attendee->get('firstName')?>">
                </div>
                <div class="form-group  mt-2">
                    <label for="lastName">Nom*</label>
                    <input type="text" id="lastName" name="lastName" class="form-control"
                        value="<?=$attendee->get('lastName')?>">
                </div>
                <div class="form-group  mt-2">
                    <label for="birthdayAt">Date de naissance*</label>
                    <input type="date" id="birthdayAt" name="birthdayAt" class="form-control"
                        value="<?=$attendee->get('birthdayAt') instanceof \DateTime ? $attendee->get('birthdayAt')->format("Y-m-d") : "" ?>">
                </div>
                <div class="form-group  mt-2">
                    <label for="email">Email*</label>
                    <input type="text" id="email" name="email" class="form-control"
                        value="<?=$attendee->get('email')?>">
                </div>
                <div class="form-group  mt-2">
                    <label for="phone">Téléphone</label>
                    <input type="text" id="phone" name="phone" class="form-control"
                        value="<?=$attendee->get('phone')?>">
                </div>
                <div class="form-group  mt-2">
                    <label for="specialityId">Specialité*</label>
                    <select class="form-select" name="specialityId" id="specialityId">
                        <?php foreach($specialities as $speciality): ?>
                        <option value=" <?=$speciality->get('id') ?>"
                            <?=$attendee->get('specialityId') && $attendee->get('specialityId') === $speciality->get('id') ? "selected": null ?>>
                            <?=$speciality->get('name') ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <input type="submit" value="<?=$editMode ? "Mettre à jour" : "Ajouter" ;?>"
                    class="btn btn-primary mx-auto my-3 mt-5 w-100">
            </form>
        </div>
    </div>
</main>
